<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @category    ViraXpress
 * @package     ViraXpress_CheckoutOptimization
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<a
    class="logo inline-flex items-center min-h-[56.4px] lg:p-[0.2em] print:mt-2 print:mb-6"
    href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
    title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $logoWidth ? 'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"' : '' ?>
            <?= $logoHeight ? 'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"' : '' ?>
    />
</a>
